import { makeStyles } from '@material-ui/core';

export default makeStyles({
  root: {
    backgroundColor: '#E5E5E5',
    display: 'flex',
    justifyContent: 'center',
    width: '100vw',
    height: '100vh',
  },
  logoSize: {
    height: '90px',
    width: '117px',
    alignSelf: 'center',
  },
  loginPaper: {
    justifyContent: 'space-around',
    alignItems: 'center',
    display: 'flex',
    alignSelf: 'center',
    flexDirection: 'column',
    width: '487px',
    height: '494px',
    left: '0%',
    right: '0%',
    bottom: '0%',
    top: '0%',
    background: '#FFFFFF',
  },
  fontStyle: {
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 500,
    fontSize: 14,
    color: '#515151',
    letterSpacing: '0.1px',
    alignSelf: 'center',
  },
  loginForm: {
    height: '300px',
    justifyContent: 'space-between',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
  },
  fieldsLogin: {
    marginLeft: '33px',
    marginRight: '33px',
    width: '421px',
    height: '52.7px',
  },
  buttonStyle: {
    background: '#018786',
    borderRadius: '4px',
    width: '179px',
    height: '40px',
    fontStyle: 'normal',
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontWeight: 500,
    fontSize: 14,
    letterSpacing: '1.25px',
  },
  errorIconStyle: {
    fontSize: 14,
  },
  errorMessageStyle: {
    display: 'flex',
    alignItems: 'center',
    fontSize: 14,
  },
});
