name: End-to-end tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - run: npm install

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - run: npx cypress version
      - run: npx cypress info
      - run: npm run e2e:ci
