# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm run build

on:
  push:
    branches:
      - main # Changing the branch here would also work
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ci-botaprarodar-web" #Must be unique in Heroku
          heroku_email: "botaprarodar.web@gmail.com"
          healthcheck: "https://ci-botaprarodar-web.herokuapp.com/health"
          checkstring: "ok"
            