# This is the workflow to push to production environment at netlify

name: Deploy to Netlify - PROD
on:
  workflow_run:
    workflows: ['Run tests - PROD']
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_KEY: ${{ secrets.PROD_REACT_APP_API_KEY }}
      REACT_APP_AUTH_DOMAIN: ${{secrets.PROD_REACT_APP_AUTH_DOMAIN}}
      REACT_APP_DATABASE_URL: ${{secrets.PROD_REACT_APP_DATABASE_URL}}
      REACT_APP_PROJECT_ID: ${{secrets.PROD_REACT_APP_PROJECT_ID}}
      REACT_APP_STORAGE_BUCKET: ${{secrets.PROD_REACT_APP_STORAGE_BUCKET}}
      REACT_APP_MESSAGING_SENDER_ID: ${{secrets.PROD_REACT_APP_MESSAGING_SENDER_ID}}
      REACT_APP_APP_ID: ${{secrets.PROD_REACT_APP_APP_ID}}
    steps:
      - uses: actions/checkout@v2
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run build --if-present

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.PROD_NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "PROD_NETLIFY_SITE_ID"]'
